# numpy array VS list

In [1]:
import numpy as np

# 1차원 배열 ( Vector 형)

In [11]:
# np array에서는 같은 자료형만 들어가야 하는 제약사항이 있지만
# ar = np.array([0,1,2,3,4,5,6,'7']) X
# 각각의 원소에 대한 접근과 반복문 실행이 빨라진다는 장점이 있다.

ar = np.array([0,1,2,3,4,5,6,7])
type(ar)

numpy.ndarray

In [12]:
# np array와는 다르게 원소 별 각각 다른 자료형을 사용할 수 있지만
# 반대로 느리다

x = [1,2,3,4,5,6,'7']
type(x)

list

In [10]:
ar * 2

TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U11') dtype('<U11') dtype('<U11')

In [13]:
x * 2

[1, 2, 3, 4, 5, 6, '7', 1, 2, 3, 4, 5, 6, '7']

# 2차원 배열 ( Matrix 형)

In [15]:
# 2 x 3 array
c = np.array([[1,2,3],
            [4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# 행의 갯수
print(len(c))

# 열의 갯수
print(len(c[0]))

2
3


In [26]:
d = list([[0,1,2],
           [4,5,6]])
d

[[0, 1, 2], [4, 5, 6]]

In [28]:
print(c*2,'\n')
print(d*2)

[[ 2  4  6]
 [ 8 10 12]] 

[[0, 1, 2], [4, 5, 6], [0, 1, 2], [4, 5, 6]]


# 3차원 배열

In [33]:
# 2 x 3 x 4
f = np.array([[[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]],
            [[1,2,3,4],
             [4,5,6,7],
             [5,2,3,4]]])
f
print('행 : ', len(f))
print('열 : ', len(f[0]))
print('깊이 : ' , len(f[0][0])) 

행 :  2
열 :  3
깊이 :  4


In [35]:
# 차원 수 반환
print(f.ndim)

# 배열의 크기 반환
print(f.shape)

3
(2, 3, 4)


# 연습문제 4.1.2

# 다음 행렬과 같은 행렬이 있다.

m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])
- 이 행렬에서 값 7 을 인덱싱한다.
- 이 행렬에서 값 14 을 인덱싱한다.
- 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
- 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
- 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [36]:
m = np.array([[0,1,2,3,4],
             [5,6,7,8,9],
             [10,11,12,13,14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
print(m[1,2], '\n')
print(m[-1,-1], '\n')
print(m[1,1:3], '\n')
print(m[1:3,2],'\n')
print(m[1:3,3:])

7 

14 

[6 7] 

[ 7 12] 

[[ 8  9]
 [13 14]]
